## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("weather_Data/clean_hotel_df.csv")
vacation_df.head()

City_ID            City Country  Max Temp Current Description      Lat  \
0        0  Saint-Philippe      RE     71.19          light rain -21.3585   
1        1           Aswan      EG     85.39           clear sky  24.0934   
2        6         Beterou      BJ     74.53          light rain   9.1992   
3        7    San Patricio      US     86.54           clear sky  28.0170   
4       12        Saraland      US     82.42       broken clouds  30.8207   

       Lng                                         Hotel Name  
0  55.7679                       Chambres d'hôte "La Trinité"  
1  32.9070                                          Nuba Nile  
2   2.2586                              Monastère de Kokoubou  
3 -97.5169                                 Motel 6 Sinton, TX  
4 -88.0706  Microtel Inn & Suites by Wyndham Saraland/Nort...

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Nassau")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Nassau")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Mount Vernon")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Westport")] 
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Bethel")] 


In [26]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
import numpy as np
start = vacation_start[["Lat", "Lng"]].to_numpy()
end = vacation_end[["Lat", "Lng"]].to_numpy()
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()
#waypoints = np.array(stop1)
#np.append(waypoints, stop2)
print(start)
print(stop1)
print(stop2)
print(stop3)
print(end)

[[ 40.7507 -73.5829]]
[[ 40.9126 -73.8371]]
[[ 41.1415 -73.3579]]
[[ 41.3712 -73.414 ]]
[[ 40.7507 -73.5829]]


In [23]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
begin = (40.7507, -73.5829)
mount_vernon = (40.9126, -73.8371)
westport = (41.1415, -73.3579)
bethel = (41.3712, -73.414)
stop = (40.7507, -73.5829)
fig = gmaps.figure()
nassau2bethel = gmaps.directions_layer(
    begin, stop, waypoints=[mount_vernon, westport, bethel, stop],
    travel_mode='DRIVING')
fig.add_layer(nassau2bethel)
fig


Figure(layout=FigureLayout(height='420px'))

In [27]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID          City Country  Max Temp Current Description      Lat  \
0      570        Nassau      US     70.83           clear sky  40.7507   
1      607  Mount Vernon      US     73.04          few clouds  40.9126   
2      193      Westport      US     70.93           clear sky  41.1415   
3      293        Bethel      US     69.67          few clouds  41.3712   

       Lng                     Hotel Name  
0 -73.5829     Hilton Garden Inn Westbury  
1 -73.8371        Ramada by Wyndham Bronx  
2 -73.3579               The Westport Inn  
3 -73.4140  Courtyard by Marriott Danbury

In [33]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [34]:
# 11a. Add a marker layer for each city to the map.
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))